name: Fly Deploy
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 */4 * * *'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Change directory
        run: cd apps/api
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
